config/routes.rb
Rails.application.routes.draw do
  resources :pets
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/pet.rb
#  name age integer gender photo breed and location

class  Pet < ApplicationRecord
  validates :name, :age, :gender, :breed, :location, presence: true
  validates_numericality_of :age, only_integer: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/pets_controller.rb
class PetsController < ApplicationController

  def new
    @pet = Pet.new
  end

  def create
    @pet = Pet.new(pet_params)
    if @pet.save
      redirect_to @pet
    else
     render 'new'
    end
  end

  def index
    @pets = Pet.all
  end

  def show
    @pet = Pet.find(params[:id])
  end

  def edit
    @pet = Pet.find(params[:id])
  end

  def update
    @pet = Pet.find(params[:id])
    if @pet.update(pet_params) 
      redirect_to @pet
    else
      render 'edit'
    end
  end 
  
  def destroy
    @pet = Pet.find(params[:id])
    @pet.destroy
    redirect_to pets_path
  end

  private
    def pet_params
      params.require(:pet).permit(:name, :age, :gender, :breed, :location)
    end

  #def find_user
   # if Pet.find_by(id: params[:id])
    #  @pet = Pet.find(params[:id])
   # else
    #  redirect_to users:path, alert:"no se encontro la mascota"
   # end   
 # end
end

app/helpers/application_helper.rb
module ApplicationHelper
	
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title DogAdoption
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/pets/_form.html.haml
= form_for @pet do |f|
  -  if @pet.errors.any?
    #error_explanation
      %h2
        = pluralize(@pet.errors.count,'error')
        ño
      %ul
        - @pet.errors.full_messages.each do |msg|
          %li
            = msg
  %p
    = f.label :Nombre
    = f.text_field :name
    = f.label :Edad
    = f.text_field :age
    = f.label :Genero
    = f.text_field :gender
    = f.label :Raza
    = f.text_field :breed
    = f.label :Localizacion
    = f.text_field :location
  %p
    = f.submit

app/views/pets/edit.html.haml
%h1
  Edita Informacion de la Mascota
= render 'form'

= link_to 'back to principal', pet_path

app/views/pets/index.html.haml
%body
.index
  %h1
    ="Mascotas en Adopción"
  = link_to 'Nueva Mascota', new_pet_path
  %table
    %tr
      %th
        ="Nombre"
      %th
        ='Edad'
      %th
        ='Género'
      %th
        ='Raza'
      %th
        ='Localización'
      %th
        =''
      %th
        =''
      %th
        =''
    - @pets.each do |pet|
      %tr
        %td
          =pet.name
        %td  
          =pet.age
        %td
          =pet.gender
        %td
          =pet.breed
        %td
          =pet.location
        %td
          =link_to 'Mostrar', pet_path(pet)
        %td
          =link_to 'Editar', edit_pet_path(pet)
        %td
          =link_to 'Eliminar', pet_path(pet),
                    method: :delete, data:{confimr: 'Are you sure?'}

app/views/pets/new.html.haml
%h1
  Nueva Mascota
= render 'form'  

app/views/pets/show.html.haml
%h1
  VAMO A MOSTRA ESTO
%p
  = @pet.name
  = @pet.age
  = @pet.gender
  = @pet.breed
  = @pet.location

= link_to 'back to principal', pets_path